### ISSUE TITLE
Building Docker issue

### ISSUE THREAD

**Issue by vladzilla** [mcheng89/gaugan#1]
Hi Michael, 
Thank you for you work doing this. 
I am tryin to make a docker image - following your instructions. 
And on both - Windows and CentOs I have an error running build.sh:

```
(gaugan) [root@localhost gaugan]# bash build.sh
Sending build context to Docker daemon  404.9MB
Step 1/9 : FROM pytorch/pytorch
 ---> f8a1d10ae3d7
Step 2/9 : COPY . /app/
 ---> 08fc13e0d95f
Step 3/9 : WORKDIR /app
 ---> Running in 2e13843f5306
Removing intermediate container 2e13843f5306
 ---> 905bde3a73a8
Step 4/9 : RUN git clone https://github.com/vacancy/Synchronized-BatchNorm-PyTorch.git
 ---> Running in b727af91f5b2
/bin/sh: 1: git: not found
The command '/bin/sh -c git clone https://github.com/vacancy/Synchronized-BatchNorm-PyTorch.git' returned a non-zero code: 127
Unable to find image 'gaugan:1.0' locally
docker: Error response from daemon: pull access denied for gaugan, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

```

Is there a way to fix it - or this project not supported anymore?
Thank you
Vlad.

**Comment by mcheng89** [comment]
Please try again:

https://github.com/mcheng89/gaugan/commit/7a282255d298187ae77f20e2a3c437c1a41d1a4d#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R6

Let me know if it works!

**Comment by vladzilla** [comment]
Hi Michael. 
so it went through and started on localhost:5000
I was a bit confused where should I put **pretrained** folder before starting buld.sh

when I press Generate Image, I see this error:
FileNotFoundError: [Errno 2] No such file or directory: '/app/pretrained/latest_net_G.pth'

I definitely did something wrong on this part of installation. 
any advice? 

Thank you
Vlad.

**Comment by vladzilla** [comment]
I've putted that folder in a couple of places and it starts working!
can close this issue!
Thank you!
V.
Great work! thank you again.
