### ISSUE TITLE
RGB - to indexed image: not an issue, question.

### ISSUE THREAD

**Issue by vladzilla** [mcheng89/gaugan#2]
Hi again Michael. )
I am trying to achieve combination of Nuke(Foundry compositing VFX software) and SPADE.
I can generate images(instance - for spade) in Nuke using RGB. but it's in rgb format(8 or 16 bit)- nuke cannot write in indexed format. 
and I can't figure out how to convert my sequence of rgb images to appropriate indexed format with values presented for coco_stuff here: https://github.com/NVlabs/SPADE/blob/master/util/coco.py
If i try photoshop - it's lots of manual rework and conversion process not clear.

Mayby you know something - since - conversion from what I paint - looks like rgb, but I understand that  there some process happens to make them in indexed format. 

by the way - your dev works well on 2080
![image](https://user-images.githubusercontent.com/7758049/98415775-c0cc4c00-2032-11eb-8098-72b9b2d8971d.png)

Thank you again
Vlad.

**Comment by mcheng89** [comment]
Please see:
https://github.com/mcheng89/gaugan/blob/master/flask/static/index.html#L161-L175
https://github.com/mcheng89/gaugan/blob/master/flask/static/index.html#L241-L255

Each color maps to the unique coco ids.

Maybe try some sort of image segmentation model to help split your RGB to coco ids: 
https://github.com/kazuto1011/deeplab-pytorch

**Comment by vladzilla** [comment]
Thank you Michael!
just for the record - if anyone like me will be asking these random questions - from Nuke they need to output only r channel in 8 bit png format(raw).
![image](https://user-images.githubusercontent.com/7758049/98428525-c89de780-2056-11eb-93dd-3aaab321b8d4.png)

Thank you.
V.
